/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecoveryIdRouteImport } from './routes/recovery.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryIdRoute = RecoveryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecoveryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escalations': typeof EscalationsRoute
  '/recovery': typeof RecoveryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/recovery/$id': typeof RecoveryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escalations': typeof EscalationsRoute
  '/recovery': typeof RecoveryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/recovery/$id': typeof RecoveryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escalations': typeof EscalationsRoute
  '/recovery': typeof RecoveryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/recovery/$id': typeof RecoveryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/escalations' | '/recovery' | '/settings' | '/recovery/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/escalations' | '/recovery' | '/settings' | '/recovery/$id'
  id:
    | '__root__'
    | '/'
    | '/escalations'
    | '/recovery'
    | '/settings'
    | '/recovery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscalationsRoute: typeof EscalationsRoute
  RecoveryRoute: typeof RecoveryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery/$id': {
      id: '/recovery/$id'
      path: '/$id'
      fullPath: '/recovery/$id'
      preLoaderRoute: typeof RecoveryIdRouteImport
      parentRoute: typeof RecoveryRoute
    }
  }
}

interface RecoveryRouteChildren {
  RecoveryIdRoute: typeof RecoveryIdRoute
}

const RecoveryRouteChildren: RecoveryRouteChildren = {
  RecoveryIdRoute: RecoveryIdRoute,
}

const RecoveryRouteWithChildren = RecoveryRoute._addFileChildren(
  RecoveryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscalationsRoute: EscalationsRoute,
  RecoveryRoute: RecoveryRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
